const SOURCES = {
  weights: ['/memory/neuronWeights.json', '../memory/neuronWeights.json'],
  coactivations: ['/memory/coactivations.json', '../memory/coactivations.json'],
  meta: ['/memory/metaNeurons.json', '../memory/metaNeurons.json'],
};

const CLUSTERS = ['emotional', 'mental', 'relational', 'actional'];
const GROWTH_LOG_LIMIT = 30;

const state = {
  previousWeights: {},
  seenNeurons: new Set(),
  growthLog: [],
};

async function fetchWithFallback(paths) {
  for (const path of paths) {
    try {
      const response = await fetch(path, { cache: 'no-store' });
      if (!response.ok) continue;
      return await response.json();
    } catch (error) {
      // Try next candidate path.
    }
  }
  return null;
}

function normalizeNeurons(weightsData, metaData) {
  const metaPatterns = metaData?.patterns || [];

  return Object.entries(weightsData || {}).map(([id, weight]) => {
    const source = metaPatterns.find((pattern) => pattern.id === id) || {};
    return {
      id,
      weight: Number(weight) || 0,
      cluster: source.cluster || source.type || 'unassigned',
      autoGenerated: Boolean(source.autoGenerated),
    };
  });
}

function renderNeurons(neurons) {
  const body = document.getElementById('neurons-body');
  if (!neurons.length) {
    body.innerHTML = '<tr><td class="empty" colspan="4">No active neurons yet.</td></tr>';
    return;
  }

  const rows = neurons
    .sort((a, b) => b.weight - a.weight)
    .map(
      (neuron) => `
      <tr>
        <td>${neuron.id}</td>
        <td>${neuron.weight.toFixed(3)}</td>
        <td>${neuron.cluster}</td>
        <td>${neuron.autoGenerated ? 'yes' : 'no'}</td>
      </tr>`,
    )
    .join('');

  body.innerHTML = rows;
}

function renderCoactivations(coactivations) {
  const body = document.getElementById('coactivation-body');

  if (!Array.isArray(coactivations) || !coactivations.length) {
    body.innerHTML = '<tr><td class="empty" colspan="3">No co-activations tracked yet.</td></tr>';
    return;
  }

  body.innerHTML = coactivations
    .map((item) => {
      const [a, b] = item.pair || [item.a, item.b, item.neuronA, item.neuronB];
      const count = item.count ?? item.weight ?? 0;
      return `
        <tr>
          <td>${a || 'unknown'}</td>
          <td>${b || 'unknown'}</td>
          <td>${count}</td>
        </tr>`;
    })
    .join('');
}

function renderClusters(neurons) {
  const clusterBars = document.getElementById('cluster-bars');
  const counts = Object.fromEntries(CLUSTERS.map((name) => [name, 0]));

  neurons.forEach((neuron) => {
    if (counts[neuron.cluster] !== undefined) counts[neuron.cluster] += 1;
  });

  const max = Math.max(1, ...Object.values(counts));

  clusterBars.innerHTML = CLUSTERS.map((cluster) => {
    const value = counts[cluster];
    const pct = Math.round((value / max) * 100);
    return `
      <div class="bar-row">
        <span>${cluster}</span>
        <div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div>
        <strong>${value}</strong>
      </div>`;
  }).join('');
}

function updateGrowthLog(neurons) {
  const now = new Date().toLocaleTimeString();
  const weightChanges = [];
  let newlyCreated = 0;

  neurons.forEach((neuron) => {
    if (!state.seenNeurons.has(neuron.id)) {
      state.seenNeurons.add(neuron.id);
      newlyCreated += 1;
    }

    const previous = state.previousWeights[neuron.id];
    if (previous !== undefined && previous !== neuron.weight) {
      const delta = neuron.weight - previous;
      weightChanges.push(`${neuron.id} ${delta > 0 ? '+' : ''}${delta.toFixed(3)}`);
    }
    state.previousWeights[neuron.id] = neuron.weight;
  });

  const logLine = {
    timestamp: now,
    newNeurons: newlyCreated,
    weightChanges: weightChanges.slice(0, 6),
  };

  state.growthLog.unshift(logLine);
  state.growthLog = state.growthLog.slice(0, GROWTH_LOG_LIMIT);

  const growth = document.getElementById('growth-log');
  growth.innerHTML = state.growthLog
    .map(
      (entry) =>
        `<li>
          <strong>${entry.timestamp}</strong> — new neurons: ${entry.newNeurons};
          weight changes: ${entry.weightChanges.length ? entry.weightChanges.join(', ') : 'none'}
        </li>`,
    )
    .join('');
}

async function renderDashboard() {
  const [weights, coactivations, meta] = await Promise.all([
    fetchWithFallback(SOURCES.weights),
    fetchWithFallback(SOURCES.coactivations),
    fetchWithFallback(SOURCES.meta),
  ]);

  const neurons = normalizeNeurons(weights || {}, meta || {});

  renderNeurons(neurons);
  renderCoactivations(coactivations || []);
  renderClusters(neurons);
  updateGrowthLog(neurons);

  const status = document.getElementById('status');
  status.textContent = `Live updates every 3s • ${new Date().toLocaleTimeString()}`;
}

renderDashboard();
setInterval(renderDashboard, 3000);
