const fs = require('fs');
const path = require('path');
const { buildTransitTags } = require('./buildTransitTags');
const {
  matchTransitToRelevantNeurons,
  loadNeuronCatalog,
  buildCompositeNarrativeSignals,
} = require('./multiNeuronMatcher');

const MEMORY_DIR = path.join(__dirname, '..', 'memory');
const CONTEXT_NEURONS_DIR = path.join(MEMORY_DIR, 'neurons');
const CONTEXT_NEURON_FILES = ['casas.json', 'signos.json', 'grados.json', 'combinaciones.json'];
const COACTIVATIONS_PATH = path.join(MEMORY_DIR, 'coactivations.json');
const WEIGHTS_PATH = path.join(MEMORY_DIR, 'neuronWeights.json');
const META_PATH = path.join(MEMORY_DIR, 'metaNeurons.json');
const BASE_NEURONS_PATH = path.join(MEMORY_DIR, 'neurons.json');

const MIN_WEIGHT = 0.1;
const MAX_WEIGHT = 1;

function readJson(filePath, fallback) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (_error) {
    return fallback;
  }
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2));
}

function clampWeight(weight) {
  return Math.min(MAX_WEIGHT, Math.max(MIN_WEIGHT, Number(weight) || MIN_WEIGHT));
}

function transitKey(transit) {
  return `${transit.planet}_${transit.target}_${transit.aspect}`.toLowerCase();
}

function comboKey(neuronIds = []) {
  return [...new Set(neuronIds)].sort().join('|');
}

function loadBaseNeurons() {
  return readJson(BASE_NEURONS_PATH, []);
}

function loadContextualNeurons() {
  if (!fs.existsSync(CONTEXT_NEURONS_DIR)) return [];

  const files = CONTEXT_NEURON_FILES.filter((file) => fs.existsSync(path.join(CONTEXT_NEURONS_DIR, file)));

  return files.flatMap((file) => readJson(path.join(CONTEXT_NEURONS_DIR, file), []));
}

function loadMetaStore() {
  return readJson(META_PATH, { patterns: [], metaSignals: [] });
}

function loadWeights() {
  return readJson(WEIGHTS_PATH, {});
}

function saveWeights(weights) {
  writeJson(WEIGHTS_PATH, weights);
}

function neuronIdFromTransit(transit) {
  return `${transit.planet}_${transit.target}_${transit.aspect}`.toLowerCase();
}

function inferClusterFromId(id = '') {
  if (/moon|emotion|reactive|frustration|sensitivity|heaviness/.test(id)) return 'emotional';
  if (/venus|relationship|relational|partnership|connection/.test(id)) return 'relational';
  if (/mercury|mind|mental|clarity|jupiter/.test(id)) return 'mental';
  return 'actional';
}

function derivedPatternOutput(firstId, secondId) {
  const firstCluster = inferClusterFromId(firstId);
  const secondCluster = inferClusterFromId(secondId);

  if (firstCluster === 'emotional' && secondCluster === 'emotional') {
    return {
      avoid: 'emotional overflow',
      focus: 'ground before engaging',
      tag: 'emotional',
    };
  }

  if (firstCluster === 'relational' && secondCluster === 'relational') {
    return {
      avoid: 'projecting unmet needs',
      focus: 'communicate from clarity',
      tag: 'relational',
    };
  }

  return {
    avoid: 'scattered energy',
    focus: 'prioritize one action',
    tag: 'actional',
  };
}

function neuronFromPattern(pattern) {
  const [first, second] = pattern.if;
  const id = `${first}_${second}_pattern`;
  const derived = derivedPatternOutput(first, second);

  return {
    id,
    if: pattern.if,
    weight: clampWeight(pattern.weight || 0.4),
    autoGenerated: true,
    output: {
      avoid: derived.avoid,
      focus: derived.focus,
    },
    tags: [derived.tag],
  };
}

function normalizeNeuron(neuron, weights) {
  const fromWeightStore = weights[neuron.id];
  return {
    ...neuron,
    weight: clampWeight(fromWeightStore ?? neuron.weight ?? neuron.peso ?? 0.4),
  };
}

function baseNeuronMatch(transit, neuron) {
  if (!neuron.if || Array.isArray(neuron.if)) return false;
  return (
    neuron.if.planet === transit.planet &&
    neuron.if.aspect === transit.aspect &&
    neuron.if.target === transit.target
  );
}

function patternNeuronMatch(activeIds, neuron) {
  if (!Array.isArray(neuron.if)) return false;
  return neuron.if.every((id) => activeIds.includes(id));
}

function normalizeContextNeuron(neuron = {}) {
  const triggers = Array.isArray(neuron.triggers)
    ? neuron.triggers
    : (Array.isArray(neuron.tags) ? neuron.tags : []);
  const tags = Array.isArray(neuron.clusters) ? neuron.clusters : (neuron.tags || ['actional']);
  return {
    ...neuron,
    triggers: triggers
      .map((tag) => String(tag || '').trim().toLowerCase())
      .filter(Boolean),
    match: neuron.match || 'all',
    minimum: Number(neuron.minimum || neuron.minimo || 1),
    tags,
    output: neuron.output || {},
  };
}

function contextualNeuronMatch(neuron = {}, transitTags = []) {
  const triggers = Array.isArray(neuron.triggers) ? neuron.triggers.filter(Boolean) : [];
  if (!triggers.length) return false;

  const normalizedTransitTags = [...new Set(transitTags
    .map((tag) => String(tag || '').trim().toLowerCase())
    .filter(Boolean))];

  const hits = triggers.filter((tag) => normalizedTransitTags.includes(tag)).length;

  if (neuron.match === 'any') return hits >= 1;
  if (neuron.match === 'flex') return hits >= Math.max(1, neuron.minimum || Math.ceil(triggers.length / 2));
  return hits === triggers.length;
}

function collectTransitTags(transit = {}) {
  const directTags = [
    ...(Array.isArray(transit.derivedTags) ? transit.derivedTags : []),
    ...(Array.isArray(transit.tags) ? transit.tags : []),
    ...(Array.isArray(transit.contextTags) ? transit.contextTags : []),
  ];

  const generated = buildTransitTags(transit);
  return [...new Set([...directTags, ...generated].filter(Boolean))];
}

function activateNeurons(transits = [], options = {}) {
  const catalog = loadNeuronCatalog();
  const selectedNeurons = [];

  transits.forEach((transit) => {
    const activation = matchTransitToRelevantNeurons(transit, catalog, options);
    const selected = [activation.primaryNeuron, ...(activation.secondaryNeurons || [])]
      .filter(Boolean)
      .map((item) => ({
        ...item.neuron,
        key: transitKey(transit),
        score: item.score,
        family: item.family,
        reasons: item.reasons,
        scoreBreakdown: item.scoreBreakdown,
      }));

    selectedNeurons.push(...selected);
  });

  const uniqueById = new Map();
  selectedNeurons.forEach((neuron) => {
    if (!neuron?.id) return;
    const current = uniqueById.get(neuron.id);
    if (!current || Number(neuron.score || 0) > Number(current.score || 0)) {
      uniqueById.set(neuron.id, neuron);
    }
  });

  const contextualActive = [...uniqueById.values()];
  const activeIds = contextualActive.map((neuron) => neuron.id);

  const weights = loadWeights();
  const metaStore = loadMetaStore();
  const patternNeurons = (metaStore.patterns || [])
    .map((pattern) => neuronFromPattern(pattern))
    .map((neuron) => normalizeNeuron(neuron, weights));

  const activePatterns = patternNeurons.filter((neuron) => patternNeuronMatch(activeIds, neuron));

  console.debug('[AstroBrain] Multi-neuron activations:', contextualActive.map((n) => `${n.id}:${(n.score || 0).toFixed(2)}`));

  return [...contextualActive, ...activePatterns];
}

function resolveTransitActivations(transits = [], options = {}) {
  const catalog = loadNeuronCatalog();
  return transits.map((transit) => ({
    transit,
    activation: matchTransitToRelevantNeurons(transit, catalog, options),
  }));
}
function logCoactivations(activeNeurons = []) {
  const ids = [...new Set(activeNeurons.map((neuron) => neuron.id).filter(Boolean))];
  if (ids.length < 2) return [];

  const coactivations = readJson(COACTIVATIONS_PATH, []);
  const event = {
    timestamp: new Date().toISOString(),
    neurons: ids,
  };
  coactivations.push(event);
  writeJson(COACTIVATIONS_PATH, coactivations);
  return coactivations;
}

function detectPatterns() {
  const coactivations = readJson(COACTIVATIONS_PATH, []);
  const counts = new Map();

  coactivations.forEach((event) => {
    const key = comboKey(event.neurons || []);
    if (!key) return;
    counts.set(key, (counts.get(key) || 0) + 1);
  });

  const patterns = [];
  counts.forEach((count, key) => {
    if (count >= 3) {
      patterns.push({
        id: `${key.replace(/\|/g, '_')}_pattern`,
        if: key.split('|'),
        weight: 0.4,
        autoGenerated: true,
      });
    }
  });

  return patterns;
}

function generateNewNeurons() {
  const detectedPatterns = detectPatterns();
  if (!detectedPatterns.length) return [];

  const metaStore = loadMetaStore();
  const existingPatternIds = new Set((metaStore.patterns || []).map((pattern) => pattern.id));
  const newPatterns = detectedPatterns.filter((pattern) => !existingPatternIds.has(pattern.id));

  if (!newPatterns.length) return [];

  const nextPatterns = [...(metaStore.patterns || []), ...newPatterns];
  writeJson(META_PATH, {
    ...metaStore,
    patterns: nextPatterns,
  });

  return newPatterns;
}

function clusterFromNeuron(neuron) {
  const id = neuron.id || '';
  const tags = neuron.tags || [];

  if (tags.includes('emotional') || /moon|emotion|reactive|frustration|saturn/.test(id)) return 'emotional';
  if (tags.includes('mental') || /mercury|mind/.test(id)) return 'mental';
  if (tags.includes('relational') || /venus|partnership|relationship/.test(id)) return 'relational';
  return 'actional';
}

function clusterNeurons(activeNeurons = []) {
  const clusters = {
    emotional: 0,
    mental: 0,
    relational: 0,
    actional: 0,
  };

  activeNeurons.forEach((neuron) => {
    const cluster = clusterFromNeuron(neuron);
    clusters[cluster] += clampWeight(neuron.weight);
  });

  return clusters;
}

function generateMetaSignals(activeNeurons = []) {
  const emotionalCount = activeNeurons.filter((neuron) => clusterFromNeuron(neuron) === 'emotional').length;
  const signals = [];

  if (emotionalCount >= 3) {
    signals.push({
      id: 'high_emotional_load',
      then: 'day emotionally intense',
    });
  }

  const metaStore = loadMetaStore();
  const historical = metaStore.metaSignals || [];

  if (signals.length) {
    writeJson(META_PATH, {
      ...metaStore,
      metaSignals: [...historical, ...signals],
    });
  }

  return signals;
}

function updateWeights(activeNeurons = [], { improvedNarrative = false } = {}) {
  if (!activeNeurons.length) return {};

  const weights = loadWeights();
  const delta = improvedNarrative ? 0.05 : -0.03;

  activeNeurons.forEach((neuron) => {
    const current = clampWeight(weights[neuron.id] ?? neuron.weight ?? 0.4);
    weights[neuron.id] = clampWeight(current + delta);
  });

  saveWeights(weights);
  return weights;
}

function pruneWeakNeurons() {
  const sessions = readJson(COACTIVATIONS_PATH, []);
  const weights = loadWeights();

  if (sessions.length < 10) return weights;

  const next = Object.entries(weights).reduce((acc, [id, weight]) => {
    if (Number(weight) >= 0.15) {
      acc[id] = weight;
    }
    return acc;
  }, {});

  saveWeights(next);
  return next;
}

function assessNarrativeRelevance({ clusterScores = {}, metaSignals = [] }) {
  const clusterTotal = Object.values(clusterScores).reduce((sum, score) => sum + score, 0);
  return clusterTotal >= 1.2 || metaSignals.length > 0;
}

module.exports = {
  activateNeurons,
  logCoactivations,
  detectPatterns,
  generateNewNeurons,
  clusterNeurons,
  generateMetaSignals,
  updateWeights,
  assessNarrativeRelevance,
  neuronIdFromTransit,
  pruneWeakNeurons,
  resolveTransitActivations,
  buildCompositeNarrativeSignals,
};
